### ISSUE TITLE
Le Wagon - BarcelonaJS

### ISSUE THREAD

**Issue by CamilaSeminario** [BarcelonaJS/event-sponsors#1]
### Sponsor Description

Le Wagon is a global leader in immersive tech training since 2013. We teach people the skills they need to land their dream job in tech, launch their startup, or change careers. Through immersive bootcamps in web development and data, we offer a life-changing learning experience.

### Sponsor Company Website

https://www.lewagon.com/

### Sponsor Company LinkedIn

https://www.linkedin.com/school/le-wagon/

### Sponsor Company Twitter

https://twitter.com/lewagonspain

### Sponsor Speaker

- [ ] Yes, we will provide a speaker

### Venue Name

Le Wagon Barcelona

### Venue Address

Carrer del Bruc 149 - 08037 Barcelona

### Venue Capacity

60 people

### Presentation Device

Projector

### Building Security Requirements

- [ ] Yes, we need to collect full names for security reasons.

### Code of Conduct and Terms and Conditions

- [X] I accept the Code of Conduct and Terms and Conditions

**Comment by onedesert** [comment]
@CamilaSeminario hello! would you be able to sponsor February event? https://github.com/BarcelonaJS/events/issues/54

**Comment by CamilaSeminario** [comment]
Hi @onedesert we are able to sponsor the February event! I just wrote you on LinkedIn

**Comment by onedesert** [comment]
Updated! https://github.com/BarcelonaJS/events/issues/54
