### ISSUE TITLE
InnoIT Consulting and Europcar

### ISSUE THREAD

**Issue by luisinnoit** [BarcelonaJS/event-sponsors#2]
### Sponsor Description

Hi, we would like to do a new event together, and this time together with Europcar. We could put one of the two speakers. As it will be in May, we can define the topic with time.

### Sponsor Company Website

https://www.inno-it.es/

### Sponsor Company LinkedIn

https://www.linkedin.com/company/innoit-consulting

### Sponsor Company Twitter

https://twitter.com/InnoitES

### Sponsor Speaker

- [X] Yes, we will provide a speaker

### Venue Name

Aticco Verdaguer

### Venue Address

C/ de Provença, 339, Barcelona

### Venue Capacity

80

### Presentation Device

Projector

### Building Security Requirements

- [X] Yes, we need to collect full names for security reasons.

### Code of Conduct and Terms and Conditions

- [X] I accept the Code of Conduct and Terms and Conditions

**Comment by dmitry-zaets** [comment]
We can not guarantee the exact month of the event, as this is done in the way of queue.

**Comment by adam-sokolowski** [comment]
@dmitry-zaets , it seems @luisinnoit submitted the proposal without informing us, and I submitted [another] after (https://github.com/BarcelonaJS/event-sponsors/issues/3) after correspondence with his colleague.
Regarding the month - does it mean you already have a speakers and the date for May?

**Comment by dmitry-zaets** [comment]
Could you let me know why you created another sponsor request instead of just adding comments to this one?

**Comment by dmitry-zaets** [comment]
In general, we accept only a single sponsor per event, otherwise, it adds confusion to both organizers team and visitors

**Comment by adam-sokolowski** [comment]
> Could you let me know why you created another sponsor request instead of just adding comments to this one?
-> https://github.com/BarcelonaJS/event-sponsors/issues/2#issuecomment-2003134610

I was not aware the first one was created until I created the other one and found this by accident

**Comment by adam-sokolowski** [comment]
> In general, we accept only a single sponsor per event, otherwise, it adds confusion to both organizers team and visitors

I understand. Then, if we change it (to EMobG being the only sponsor), will you accept both our speakers?

**Comment by onedesert** [comment]
No, we have 2 talk spots per event, and in respect to our community speakers we limit sponsors to 1 talk, so we also allow 1 talk submitted by the community. I will only be the case if we haven't had any application from the community, but as you can see [here](https://github.com/BarcelonaJS/talks/issues) we have 8 in the queue.

**Comment by adam-sokolowski** [comment]
@onedesert, thank you for clarification! I'll talk to our director and will adjust our plan!
