### ISSUE TITLE
BarcelonaJS May - May 29th, 18:30

### ISSUE THREAD

**Issue by adam-sokolowski** [BarcelonaJS/event-sponsors#3]
### Sponsor Description

Europcar Mobility Group (EMobG)

EMobG is a major mobility solutions provider with multiple brands, operations in 140 countries, a headquarters in Paris, and a significant portion of the front-end engineering team based in Barcelona.

### Sponsor Company Website

https://europcar-mobility-group.com/

### Sponsor Company LinkedIn

https://www.linkedin.com/company/europcar-mobility-group/mycompany/ 

### Sponsor Company Twitter

- none

### Sponsor Speaker

- [X] Yes, we will provide a speaker

### Venue Name

Cloudworks Urquinaona https://wearecloudworks.com/coworking/urquinaona/

### Venue Address

Rda. de Sant Pere, 52, 6a Planta, 08010 Barcelona

### Venue Capacity

50

### Presentation Device

Projector

### Building Security Requirements

- [X] Yes, we need to collect full names for security reasons.

### Code of Conduct and Terms and Conditions

- [X] I accept the Code of Conduct and Terms and Conditions

**Comment by adam-sokolowski** [comment]
@dmitry-zaets @onedesert We would like to provide two speakers (so, two presentations) - one focused on front-end, the other, from InnoIt (and this is preliminary topic), about strategy for success in the tech interview.

I saw @dmitry-zaets comment [here](https://github.com/BarcelonaJS/event-sponsors/issues/2), and I'd like to ask what are the chances of our event taking place in May. How can we coordinate that? None of us (neither EMobG nor InnoIt) owns the venue and we need to book it in advance.

**Comment by dmitry-zaets** [comment]
Is there any specific reason why you've created a duplicated sponsorship request (duplicate from InnoIt https://github.com/BarcelonaJS/event-sponsors/issues/2)
