### ISSUE TITLE
Europcar Mobility Group (EMobG)

### ISSUE THREAD

**Issue by adam-sokolowski** [BarcelonaJS/event-sponsors#4]
### Sponsor Description

Europcar Mobility Group (**EMobG**) is a major mobility solutions provider with multiple brands (among them Europcar, Ubeeqo, and Goldcar), operations in 140 countries, and headquarters in Paris. The majority of the front-end engineering team is based in Barcelona, and we are leading the development of the group's user interfaces and interactive features for EMobG's digital platforms.

### Sponsor Company Website

https://europcar-mobility-group.com/

### Sponsor Company LinkedIn

https://www.linkedin.com/company/europcar-mobility-group/

### Sponsor Company Twitter

- 

### Sponsor Speaker

- [X] Yes, we will provide a speaker

### Venue Name

Cloudworks Urquinaona

### Venue Address

Rda. de Sant Pere, 52, 6a Planta, 08010 Barcelona

### Venue Capacity

60

### Presentation Device

Projector

### Building Security Requirements

- [X] Yes, we need to collect full names for security reasons.

### Code of Conduct and Terms and Conditions

- [X] I accept the Code of Conduct and Terms and Conditions

**Comment by adam-sokolowski** [comment]
@dmitry-zaets @onedesert We can negotiate the exact time and date, but not by much. Please, let me know if this is an acceptable proposal. I was rather conservative in terms of spots available, and we can even stretch it to 60.

**Comment by dmitry-zaets** [comment]
Sponsor proposed date: BarcelonaJS May - May 29th, 18:30

**Comment by onedesert** [comment]
As a general rule, we can accomodate on date, but we are strict on 19h as event start time.

**Comment by adam-sokolowski** [comment]
@onedesert, Thank you. I agree,  I'm OK with 19:00.

**Comment by dmitry-zaets** [comment]
@adam-sokolowski Would Europcar be available for May 30th, 19:00? (Thursday)

**Comment by adam-sokolowski** [comment]
@dmitry-zaets , Yes, we can do that 
May 30th, 19:00 (Thursday).

When do you need the title of my presentation? Should I create a proposal?

**Comment by dmitry-zaets** [comment]
Great!
yep, feel free to create a proposal and we will connect it to the event

**Comment by adam-sokolowski** [comment]
@dmitry-zaets I created [this proposal](https://github.com/BarcelonaJS/talks/issues/14)

**Comment by dmitry-zaets** [comment]
Great!

**Comment by dmitry-zaets** [comment]
Assigned the talk to the event
