### ISSUE TITLE
Tree Nation

### ISSUE THREAD

**Issue by FrankIglesias** [BarcelonaJS/event-sponsors#6]
### Sponsor Description

Our job at Tree-Nation is to make sure more trees are planted every day.

700,000 citizens and 19,000 companies already joined Tree-Nation and together we have planted more than 37,000,000 trees in 25 different countries.

Through Tree-Nation, citizens and companies can compensate for their CO2 emissions by planting trees around the world and offering them to friends, clients, and employees with our email tree-gift tool.

Reforestation projects use Tree-Nation to raise funds and communicate about their tree planting activities to the world.

We want to make tree planting easy and accessible to everyone. And we mean everyone. It just happens that, with climate change, humanity is possibly facing its biggest threat ever. We believe our platform can help by uniting all tree planting efforts worldwide and providing a safe and enjoyable tree-planting experience.

For this task, we are lucky to receive the help of so many amazing people that participate, one way or another, in making this global reforestation goal a reality.

### Sponsor Company Website

tree-nation.com

### Sponsor Company LinkedIn

https://www.linkedin.com/company/tree-nation/

### Sponsor Company Twitter

https://x.com/treenation?lang=en

### Sponsor Speaker

- [X] Yes, we will provide a speaker

### Venue Name

Nest City Lab

### Venue Address

C. d'Àlaba, 100, Sant Martí, 08018 Barcelona

### Venue Capacity

40 - 45 people

### Presentation Device

TV

### Building Security Requirements

- [X] Yes, we need to collect full names for security reasons.

### Code of Conduct and Terms and Conditions

- [X] I accept the Code of Conduct and Terms and Conditions

**Comment by onedesert** [comment]
Hello, thanks for your application, is there any preference on a month to sponsor? Also, the venue is a bit small for our events, is that the full capacity? Thanks.

**Comment by FrankIglesias** [comment]
Hello Yan! Thanks for the reply! 
Mid July onwards is good for us. In terms of space can go a little bit higher but thats the full capacity for everyone sat in front of a proyector. More people can fit. But standing

**Comment by dmitry-zaets** [comment]
@FrankIglesias Let's schedule for July?

**Comment by FrankIglesias** [comment]
Sure!

**Comment by dmitry-zaets** [comment]
Assigned to https://github.com/BarcelonaJS/events/issues/60
